/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#adc6ff",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-container": "#4d8eff",
        "surface-bright": "#353942",
        "surface-container-high": "#262a33",
        "tertiary-fixed-dim": "#ffb786",
        "on-secondary-fixed": "#07006c",
        "on-primary-fixed-variant": "#004395",
        "surface-container": "#1c2028",
        "on-error": "#690005",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#adc6ff",
        "surface": "#0f131c",
        "surface-container-lowest": "#0a0e16",
        "on-tertiary": "#502400",
        "tertiary-fixed": "#ffdcc6",
        "surface-container-highest": "#31353e",
        "on-primary-fixed": "#001a42",
        "surface-container-low": "#181c24",
        "error": "#ffb4ab",
        "secondary-container": "#3131c0",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-container": "#461f00",
        "on-secondary": "#1000a9",
        "outline-variant": "#424754",
        "inverse-on-surface": "#2c3039",
        "on-tertiary-fixed-variant": "#723600",
        "on-primary": "#002e6a",
        "on-tertiary-fixed": "#311400",
        "background": "#0f131c",
        "primary-fixed": "#d8e2ff",
        "error-container": "#93000a",
        "surface-dim": "#0f131c",
        "on-error-container": "#ffdad6",
        "on-background": "#dfe2ee",
        "surface-variant": "#31353e",
        "on-primary-container": "#00285d",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-container": "#df7412",
        "outline": "#8c909f",
        "tertiary": "#ffb786",
        "on-surface-variant": "#c2c6d6",
        "primary": "#adc6ff",
        "on-surface": "#dfe2ee",
        "inverse-primary": "#005ac2",
        "secondary": "#c0c1ff",
        "inverse-surface": "#dfe2ee"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin": "3rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"],
        "display-hero": ["Geist", "sans-serif"],
        "code-snippet": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "code-snippet": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
